### ISSUE TITLE
How the dictionary was created

### ISSUE THREAD

**Issue by fbertola** [benoit-pierre/plover_michela#1]
It would be really helpful if you could provide the script/code to populate new dictionary entries. I wrote a simple pipeline to convert word to phonemes, then syllables to chords; unfortunately the results does not align.

**Comment by Sillabix** [comment]
The dictionary was not generated using a script / code and is not simply a transposition of the syllables because, deriving from professional dictionaries, abbreviations and briefs are used.

**Comment by benoit-pierre** [comment]
@fbertola: I'll assume this answer your question.
