### ISSUE TITLE
Grammar rules to apply suffixes

### ISSUE THREAD

**Issue by Sillabix** [benoit-pierre/plover_michela#3]
As for the English stenotype plugin, would be useful to provide the system with some grammar rules to correctly apply suffixes and word endings. E. g. "amare" + ^ti = "amarti", "portano" + ^dole = "portandole", "contatto" + ^ti = "contatti".

**Comment by benoit-pierre** [comment]
Just provide me the rules and I'll add them to the system.

**Comment by Sillabix** [comment]
Just one question. On Eclipse, after the rules are applied the program
checks if the word is correct against a spelling dictionary. I suppose
Plover does the same. Is it so?

Il giorno mar 13 nov 2018, 15:58 Benoit Pierre <notifications@github.com>
ha scritto:

**Comment by benoit-pierre** [comment]
Yes, using a [simple wordlist](https://raw.githubusercontent.com/openstenoproject/plover/master/plover/assets/american_english_words.txt).

**Comment by Sillabix** [comment]
Ok, so I guess I should provide an Italian wordlist big enough to act as a
spelling dictionary...

Il giorno mar 13 nov 2018, 17:54 Benoit Pierre <notifications@github.com>
ha scritto:

**Comment by benoit-pierre** [comment]
Note that the words are ranked, so more common words get priority: if multiple orthography rules can be applied, the most common resulting word will be chosen.

**Comment by Sillabix** [comment]
In Eclipse, the prefixes and suffixes rules work in a bit different way.
The priority of the rule is given by the order you put it in the list. Then
the software follows the list and try to applies the various rules until it
found a corrispondence in the spelling dictionary. Here is a brief summary
of the Eclipse syntax used in  prefixes suffixes table:

& will double the last letter of the root word;

^ will delete a letter from the root word;

letters in brackets [] limit the ability of carets to delete letters; only
these letters may be deleted. ^[e]ine will delete one letter, but only if
that letters is E. Multiple letters may be used;

letters in brackets and preceded with an equal sign [=] mean that letters
will only be deleted if they appear in this exact sequence.  ^^[=ed] would
delete the letters "ed", but nothing else, and would not delete any
combination of these letters such as "de".  This only makes sense if it
deletes more than one character with more carets;

letters not in brackets are simply attached to the root word.  ^ing will
delete a letter, and then add "ing" to the root word.

So,for istance, the rule for the suffix "bility" is the following:

^ability=&ability,&ibility,ability,ibility,^[e]ability,^[e]ibility,^[y]iability.
&ability,&ibility,ability,ibility

The priority is given by the order of the entries not by the word ranking.
So, looking at the rule above, the program will first try to apply the
suffix "ability" doubling the last letter of the root word and checking it
against a spelling dictionary to see if it exists. If it doesn't exists,
the program will try with "ibility", always doubling the last letter of the
root word and checking against the spelling dictionary. If also this word
doesn't exist, it will try to apply "ability" without doubling the last
letter and deleting one character  (onoy if it corresponds to an "e") of
the root word and checking  the spelling dictionary. And so on... The list
of rules can be changed by each user so each user can decide the best
priorities for the various prefix/suffixes. It's not a bad system in my
opinion.


In any case for the Michela the rules would

Il giorno mar 13 nov 2018, 21:39 Benoit Pierre <notifications@github.com>
ha scritto:

**Comment by Sillabix** [comment]
For the moment it would be enough to have just a simple rule for suffixes similar to the one used with commercial steno softwares which goes like this:

^ti = ti,^ti, ^^ti

which means: when there is the suffix "^ti", try to apply it to the end of the previous word. If no words are found in the wordlist, try to delete the last character of the previous word and check it on the wordlist. If there isn't any word found in the wordlist, try to delete the two last characters of the previous word and check it on the wordlist. If no words are found also in this case, just apply the suffix as is. So with this rules would be possible to write word like "portata-mi" (portata+mi), portarmi" (portare+mi) and "affermi" (afferro+mi).

**Comment by Sillabix** [comment]
Or, if that rule is not possible, could just be fine to have a single rule to apply the suffix to the root word just deleting one (or two) character from the end. This rule should be applied to the following suffixes:^ce, ^ci, ^la, ^le, ^li, ^lo, ^mi, ^ne, ^se, ^si, ^so, ^te, ^ti, ^dola, ^dole, ^doli, ^dolo.
