### ISSUE TITLE
English adaptation?

### ISSUE THREAD

**Issue by KoolenDasheppi** [benoit-pierre/plover_michela#4]
Is there an English dictionary/adaptation for this system? I have a midi keyboard, and I'd like to use it for stenography.

**Comment by Sillabix** [comment]
I've written a Michela-English theory based on the original Michela-English alphabet created by the inventor. I also started to write down an English Plover dictionary. At the moment it counts just 1000 words but I hope to enlarge it soon.

**Comment by kool601** [comment]
So is it going to be released sometime soon?

**Comment by Sillabix** [comment]
Yes, I should put it on my Github repository. It would be useful to have some English speaking people giving it a try and, perhaps, helping me in enlarging the dictionary.

**Comment by Sillabix** [comment]
Ok, are you also on the Plover-Discord server?

**Comment by kool601** [comment]
No, but I'll join it right now. If you have a link, you can post it here, but if not I can look for it.

**Comment by kool601** [comment]
I found it and am joined. My name's Koolen on there, same profile picture as here. ^w^

**Comment by Sillabix** [comment]
I found you. I'll send you a PM.

**Comment by Sillabix** [comment]
Here is the draft of the first part of the Michela MIDI English theory.


https://github.com/Sillabix/Michela-steno-keyboard-dictionaries-and-documents/blob/master/Fast%20writing%20with%20piano%20chords%20(draft%20-%20lesson%20I-X).pdf

**Comment by davidedelvento** [comment]
The previous link is broken but I found the document. For people less patient than me here is the direct link: https://github.com/Sillabix/Michela-stenotype-keyboard-miscellaneous-files-/raw/master/Phonographic%20and%20phonostenographic%20Michela%20symbols.pdf

**Comment by Sillabix** [comment]
No, that link is not to the theory but to a document about the original phonographic Michela theory. 

The correct link to the English-phonetic theory is this:
https://github.com/Sillabix/Michela-phonetic-shorthand-theory-for-English-under-construction
