### ISSUE TITLE
Error with orthographic dictionary after installing the Michela plugin

### ISSUE THREAD

**Issue by Sillabix** [benoit-pierre/plover_michela#6]
After installing the Michela plugin with Plover 4.0.0.dev10+2.g0501aa3 it appears this error when you restart the program: 

AssertionError: C:\Users\Compadmin_Asus\AppData\Local\plover\plover\plugins\win\Python38\site-packages\plover_michela\assets\italian_words.txt contains duplicate words.

**Comment by benoit-pierre** [comment]
Fixed in 1.0.1.

**Comment by Sillabix** [comment]
Great! 👏👏👏
