### ISSUE TITLE
New upgraded dictionaries to put in the plugin

### ISSUE THREAD

**Issue by Sillabix** [benoit-pierre/plover_michela#7]
Hi, we have made a complete revision and improvement of the Michela theory for Plover. The new manual has been uploaded to Github. These are the files updated to the new theory that we would like to see uploaded in the michela plugin.

[Michela upgraded theory files.zip](https://github.com/benoit-pierre/plover_michela/files/8566018/Michela.upgraded.theory.files.zip)

**Comment by benoit-pierre** [comment]
Can you give me a brief explanation of what changed? (For the release notes).

**Comment by Sillabix** [comment]
Yes, sorry not to mention them.

 The Michela-Plover theory has been updated to take full advantage of the inflectional suffixes based on grammar rules recently introduced.  In particular:

1) has been modified the rules to indicate the endings of the words "e" and "i"  in order to avoid a series of conflicts caused by th previous system based on diphthong (for a full description refer to the Michela theory manual on Github);

2) the stroke for the numeric dictionary has been changed (from "IU" to "Uu") in order to avoid a series of possible conflicts; 

3) the syllabic fingerspelling system has been modified (it uses now the combination "RX" and "RXI" for capital letters);

4) have been emended numerous definitions relating to prefixes and suffixes and formatting commands.

**Comment by benoit-pierre** [comment]
OK, so I'm going to copy that info in the note pretty much verbatim, and bump the version to 2.0.0 (as it seems like a pretty major change), agreed?

**Comment by benoit-pierre** [comment]
Preview:

### 2.0.0

* The theory has been updated to take full advantage of the inflectional suffixes
  based on grammar rules recently introduced. In particular:
  - The rules to indicate the endings of the words "e" and "i" have been modified
    to avoid a conflicts caused by the previous diphthong-based system (for a
    full description refer to the Michela theory manual on GitHub).
  - The numeric dictionary' strokes have been changed (from `IU` to `Uu`) in
    order to avoid a series of possible conflicts.
  - The syllabic finger-spelling system has been modified: it now uses the
    combination `RX` and `RXI` for capital letters.
* Numerous definitions relating to prefixes / suffixes and formatting commands have been amended.

**Comment by Sillabix** [comment]
Yes, is a major change, so Ver. 2.0.0 is ok.
Just spotted a little typing error in the description "a conflicts"

**Comment by benoit-pierre** [comment]
Version `2.0.0` is live.

**Comment by Sillabix** [comment]
Great! Thanks a lot.
